### PR TITLE
 Bug Report #24 - vacancy creation redirect on submit

### PR DESCRIPTION
**Pull request by ZajithCorro**
## Checklist

- [X] I have followed the [contributor guideline](https://github.com/Platzi-Master-C8/gethired-base/blob/main/CONTRIBUTING.md)
- [ ] Tests are included
- [ ] Documentation is changed or added
- [X] Related issue has been created
- [X] Commits messages follows [commit guideline](https://github.com/Platzi-Master-C8/gethired-base/blob/main/CONTRIBUTING.md/#Commits)

### Type of PR

- [X] Feature
- [ ] Bugfix
- [ ] Hotfix
- [ ] Chore

### Merge strategy

- [X] Squash (default)
- [ ] Merge commit (branch merges, usually used for merges to master)
- [ ] Rebase (preserve individual commits without merge commit)

### Purpose

> 
### Relevant tickets

> resolves [#24]

### Related PR's

> 
### Screenshots

>

### CODE REVIEW

**Review by odagora — APPROVED** [review]

**Comment by odagora** [comment]
Perfect!. The alert only shows if there is an error

**Comment by ferchodeleon** [comment]
I don't see drawbacks. :)

**Review by ferchodeleon — APPROVED** [review]
I don't see drawbacks. :)

**Review by LeoCode0 — COMMENTED** [review]
Everything looks good!

**Pull request merged**
